TPL_SSH_CONFIG="Host $SERVER_HOST
  HostName $SERVER_HOST
  User $SERVER_USER
  Port $SERVER_PORT
  IdentityFile ~/.ssh/$CLIENT_RSA_KEY_NAME
  LogLevel ERROR"

TPL_MAIL_CONFIG="root=$MAIL_SENDER_ADDRESS
mailhub=$MAIL_SERVER_HOST:$MAIL_SERVER_PORT
FromLineOverride=YES
AuthMethod=LOGIN
AuthUser=$MAIL_AUTH_USER
UseTLS=$MAIL_TLS
UseSTARTTLS=$MAIL_STARTTLS"
